-- Driver App用 jobs テーブル定義
-- Supabaseの SQL Editor で実行してください

CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- 必須カラム
    driver_name TEXT,              -- "佐藤さん" 等 (BoardCanvasのdriver.nameと一致)
    status TEXT DEFAULT '未着手',   -- 未着手, 作業中, 完了, 出発済, 帰社済
    type TEXT DEFAULT 'pickup',    -- pickup, depot
    
    -- 案件詳細
    customer TEXT,                 -- 顧客名
    address TEXT,                  -- 住所 (Mapsリンク用)
    special_notes TEXT,            -- 特記事項
    
    -- JSONデータ (柔軟性確保)
    job_contents JSONB DEFAULT '[]'::jsonb, -- 回収品目 [{name: '段ボール', weight: 450}]
    work_tasks JSONB DEFAULT '[]'::jsonb    -- 拠点作業 [{text: '掃除', completed: false}]
);

-- RLS (Row Level Security) 設定
-- 開発中は全開放、本番時は要制限
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.jobs
    FOR SELECT USING (true);

CREATE POLICY "Enable insert access for all users" ON public.jobs
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update access for all users" ON public.jobs
    FOR UPDATE USING (true);
