-- 【重要】既存の jobs テーブルを削除して再作成します
-- ※既存のデータは消えますのでご注意ください

DROP TABLE IF EXISTS public.jobs;

CREATE TABLE public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- 必須カラム
    driver_name TEXT,              -- フィルタ用
    status TEXT DEFAULT '未着手',
    type TEXT DEFAULT 'pickup',
    
    -- 案件詳細
    customer TEXT,
    address TEXT,
    special_notes TEXT,
    
    -- JSONデータ
    job_contents JSONB DEFAULT '[]'::jsonb,
    work_tasks JSONB DEFAULT '[]'::jsonb
);

-- RLS設定
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.jobs
    FOR SELECT USING (true);

CREATE POLICY "Enable insert access for all users" ON public.jobs
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update access for all users" ON public.jobs
    FOR UPDATE USING (true);
